name: Test site build

on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk

jobs:
  test_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@7db63f5e7f65f5c06a64fd56106389606f84a976
        with:
          hugo-version: '0.110.0'
          extended: true
      - name: Build
        run: chmod +x build-site.sh && ./build-site.sh
        env:
          SELENIUM_CI_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
